workflows:
  ios-testflight:
    name: iOS TestFlight Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Codemagic Key"
    environment:
      groups:
        - appstore_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on macOS builder
        script: |
          set -e
          keychain initialize
          app-store-connect fetch-signing-files "com.kaan.robopet" \
            --type IOS_APP_STORE \
            --certificate-key @env:CERTIFICATE_PRIVATE_KEY \
            --create || { echo "Codemagic failed to fetch signing files from Apple! Look at the error above."; exit 1; }
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Flutter iOS app
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner" --config "Release"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
