workflows:
  ios-testflight:
    name: iOS TestFlight Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Codemagic Key"
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on macOS builder
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.kaan.robopet" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Flutter iOS app
        script: |
          flutter build ios --release --no-codesign
          xcodebuild archive -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/ios/xcarchive/Runner.xcarchive CODE_SIGN_STYLE=Manual COMPILER_INDEX_STORE_ENABLE=NO
          xcodebuild -exportArchive -archivePath build/ios/xcarchive/Runner.xcarchive -exportPath build/ios/ipa -exportOptionsPlist /Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
