workflows:
  ios-testflight:
    name: iOS TestFlight Build
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "Codemagic Key"
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on macOS builder
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.kaan.robopet" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Flutter iOS app
        script: |
          flutter build ios --release --no-codesign
          
          cat <<EOF > custom_export_options.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>manageAppVersionAndBuildNumber</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF
          
          PROFILE_PATH=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" | head -n 1)
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
          TEAM_ID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:com.apple.developer.team-identifier' /dev/stdin <<< $(security cms -D -i "$PROFILE_PATH"))
          
          echo "Using Profile UUID: $PROFILE_UUID"
          echo "Using Team ID: $TEAM_ID"
          
          xcodebuild archive -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/ios/xcarchive/Runner.xcarchive CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" DEVELOPMENT_TEAM="$TEAM_ID" COMPILER_INDEX_STORE_ENABLE=NO
          xcodebuild -exportArchive -archivePath build/ios/xcarchive/Runner.xcarchive -exportPath build/ios/ipa -exportOptionsPlist custom_export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
