// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ9eUY1dvrCvWGdRchPIlQxCMRvIQuua4',
    appId: '1:198832235665:web:8ed2d1339122fe4d5ecb30',
    messagingSenderId: '198832235665',
    projectId: 'my-robo-dog',
    authDomain: 'my-robo-dog.firebaseapp.com',
    storageBucket: 'my-robo-dog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwJw5yfnki7EYQpTmNgf9cKow6laAwrVc',
    appId: '1:198832235665:android:00edefa734037ba65ecb30',
    messagingSenderId: '198832235665',
    projectId: 'my-robo-dog',
    storageBucket: 'my-robo-dog.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHtsjeTUzhqp5IXfMiEUyF5lvEIncEldo',
    appId: '1:198832235665:ios:463892dc11ed97c85ecb30',
    messagingSenderId: '198832235665',
    projectId: 'my-robo-dog',
    storageBucket: 'my-robo-dog.firebasestorage.app',
    iosBundleId: 'com.kaan.robopet',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHtsjeTUzhqp5IXfMiEUyF5lvEIncEldo',
    appId: '1:198832235665:ios:463892dc11ed97c85ecb30',
    messagingSenderId: '198832235665',
    projectId: 'my-robo-dog',
    storageBucket: 'my-robo-dog.firebasestorage.app',
    iosBundleId: 'com.kaan.robopet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ9eUY1dvrCvWGdRchPIlQxCMRvIQuua4',
    appId: '1:198832235665:web:0ffdda2e794a35475ecb30',
    messagingSenderId: '198832235665',
    projectId: 'my-robo-dog',
    authDomain: 'my-robo-dog.firebaseapp.com',
    storageBucket: 'my-robo-dog.firebasestorage.app',
  );
}
